### ISSUE TITLE
Launch dialog > "Working directory" not working

### ISSUE THREAD

**Issue by Zeugma440** [AndreiFedarets/chronosprofiler#3]
Hi there,

I'm trying to use release 0.4.1 to analyze a console app (generated with x86 debug)

Once Chronos Profiler is installed by the MSI, I did the following : 

1. Run Chronos.Client.Win/Chronos.Client.Win.Application.exe
2. Select "Desktop app"
3. Select my app as the executable
4. Type a specific working directory as the working directory
5. Hit "Create"

Unfortunately, when `Console.WriteLine(Environment.CurrentDirectory);` displays the Chronos working directory, and not the one I typed.

**Comment by AndreiFedarets** [comment]
Fixed. Target version 0.4.2
